### ISSUE TITLE
The package "demest" cannot be installed, why?

### ISSUE THREAD

**Issue by rmdxlq** [StatisticsNZ/demest#1]
All the previous packages can be installed, except "demest". 
The message said "
** R
Error in parse(outFile) : 
  C:/Users/user/AppData/Local/Temp/Rtmp8yIfSC/devtools12ec72223492/StatisticsNZ-demest-8f4c9f0/R/CMP-functions.R:303:1: 意外的'}'
302: # it can be modified of course
303: }
     ^
ERROR: unable to collate and parse R files for package 'demest'
* removing 'C:/Users/user/Documents/R/win-library/3.4/demest'
Installation failed: Command failed (1)
"
Is it the "}" in line 303 ?
How can it be fixed?
Thanks very much.

**Comment by johnrbryant** [comment]
Apologies! We mixed up our branches on github. The package should install now.

John

John Bryant
Senior Researcher | Kairangahau Matua
Stats NZ Tatauranga Aotearoa
DDI +64 3 964 8326 | stats.govt.nz<http://www.stats.govt.nz/>
[cid:image001.png@01D35468.B1837230]<http://www.stats.govt.nz/about_us.aspx>
[cid:image002.png@01D35469.664762D0]<https://www.facebook.com/StatisticsNZ>  [cid:image003.png@01D35469.664762D0] <https://twitter.com/StatisticsNZ>   [cid:image004.png@01D35469.664762D0] <https://www.linkedin.com/company/statistics-new-zealand>

**Comment by rmdxlq** [comment]
Thanks a lot!
